##Задача регрессии для SI (Selectivity Index)
Аналогично предыдущим задачам, мы будем предсказывать логарифмированный индекс селективности ( pSI=log10(SI) ) и сравнивать эффективность моделей.

In [8]:
!pip install optuna -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 26.8 MB/s eta 0:00:00

In [9]:
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import mean_squared_error
import lightgbm as lgb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score
import xgboost as xgb
import seaborn as sns
import lightgbm as lgb
from sklearn.model_selection import KFold, cross_validate
import optuna

In [10]:


# Load the dataset
file_path = '/content/cleaned_molecular_data.csv'
df = pd.read_csv(file_path)

# Display basic information
print("Dataset Shape:", df.shape)
display(df.head())
print(df.info())

Dataset Shape: (966, 214)

,"IC50, mM","CC50, mM",SI,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea,is_outlier
0,6.239374,175.482382,28.125000,5.094096,5.094096,0.387225,0.387225,0.417362,42.928571,384.652,...,0,0,0,0,0,0,0,3,0,1
1,0.771831,5.402819,7.000000,3.961417,3.961417,0.533868,0.533868,0.462473,45.214286,388.684,...,0,0,0,0,0,0,0,3,0,1
2,223.808778,161.142320,0.720000,2.627117,2.627117,0.543231,0.543231,0.260923,42.187500,446.808,...,0,0,0,0,0,0,0,3,0,1
3,1.705624,107.855654,63.235294,5.097360,5.097360,0.390603,0.390603,0.377846,41.862069,398.679,...,0,0,0,0,0,0,0,4,0,1
4,107.131532,139.270991,1.300000,5.150510,5.150510,0.270476,0.270476,0.429038,36.514286,466.713,...,0,0,0,0,0,0,0,0,0,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 966 entries, 0 to 965
Columns: 214 entries, IC50, mM to is_outlier
dtypes: float64(107), int64(107)
memory usage: 1.6 MB
None

In [11]:
# 1. Подготовка данных для SI
target_si = 'SI'
exclude_cols_si = ['IC50, mM', 'CC50, mM', 'SI', 'IC50_above_median', 'CC50_above_median', 'SI_above_median', 'SI_above_8', 'is_outlier']
# SI расчитывается из CC50 IC50 , я понял задачу как построение регресии без этих предикторов (так как это целевые переменные задачи 1 и 2)
# , если же их использование возможно , то из списка выше их нужно было бы исключить
# Признаки
relevant_features_si = [col for col in df.select_dtypes(include=[np.number]).columns if col not in exclude_cols_si]

# Убираем NaN в SI (если есть) и логарифмируем
df_si = df.dropna(subset=[target_si]).copy()
df_si = df_si[df_si[target_si] > 0] # SI должен быть больше 0 для логарифмирования

X_si = df_si[relevant_features_si]
y_si_log = np.log10(df_si[target_si])

X_train_si, X_test_si, y_train_si, y_test_si = train_test_split(X_si, y_si_log, test_size=0.2, random_state=42)

print(f"Samples for SI task: {len(df_si)}")

Samples for SI task: 966

### Базовые модели (стандартные параметры) для SI

In [14]:
standard_models = {
    "GBR (Default)": GradientBoostingRegressor(random_state=42),
    "RF (Default)": RandomForestRegressor(random_state=42),
    "LGBM (Default)": lgb.LGBMRegressor(random_state=42, verbosity=-1)
}
baseline_si = []
for name, model in standard_models.items():
    model.fit(X_train_si, y_train_si)
    tr_p= model.predict(X_train_si)
    te_p = model.predict(X_test_si)
    baseline_si.append({
        "Model": name,
        "Train RMSE": np.sqrt(mean_squared_error(y_train_si, tr_p)),
        "Test RMSE": np.sqrt(mean_squared_error(y_test_si, te_p)),
        "Test R2": r2_score(y_test_si, te_p)
    })
display(pd.DataFrame(baseline_si))

            Model  Train RMSE  Test RMSE   Test R2
0   GBR (Default)    0.483795   0.666920  0.196010
1    RF (Default)    0.400265   0.664826  0.201051
2  LGBM (Default)    0.369449   0.691354  0.136020

In [ ]:
def run_optuna_si(model_class, n_trials=200):
    def objective(trial):
        if model_class == GradientBoostingRegressor:
            params = {
                'n_estimators': trial.suggest_int('n_estimators', 50, 300),
                'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
                'max_depth': trial.suggest_int('max_depth', 3, 7),
                'random_state': 42
            }
        elif model_class == RandomForestRegressor:
            params = {
                'n_estimators': trial.suggest_int('n_estimators', 50, 300),
                'max_depth': trial.suggest_int('max_depth', 5, 15),
                'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
                'random_state': 42
            }
        else: # LGBM
            params = {
                'n_estimators': trial.suggest_int('n_estimators', 50, 300),
                'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
                'num_leaves': trial.suggest_int('num_leaves', 20, 60),
                'random_state': 42, 'verbosity': -1
            }

        model = model_class(**params)
        kf = KFold(n_splits=4, shuffle=True, random_state=42)
        cv = cross_validate(model, X_train_si, y_train_si, cv=kf, scoring='neg_mean_squared_error', return_train_score=True)
        val_rmse = np.mean(np.sqrt(-cv['test_score']))
        train_rmse = np.mean(np.sqrt(-cv['train_score']))
        return val_rmse - 2 * abs(val_rmse - train_rmse)

    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=n_trials)
    return study.best_params

print("Tuning models for SI...")
best_gbr_si = run_optuna_si(GradientBoostingRegressor)
best_rf_si = run_optuna_si(RandomForestRegressor)
best_lgbm_si = run_optuna_si(lgb.LGBMRegressor)

[I 2026-05-23 10:35:09,252] A new study created in memory with name: no-name-679ccf35-c10f-442a-91cb-d230e1ad5c49

Tuning models for SI...

[I 2026-05-23 10:35:25,909] Trial 0 finished with value: 0.5829875372366307 and parameters: {'n_estimators': 147, 'learning_rate': 0.005006860441970198, 'max_depth': 4}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:35:37,963] Trial 1 finished with value: 0.5088255365917665 and parameters: {'n_estimators': 72, 'learning_rate': 0.009001334857397954, 'max_depth': 6}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:36:09,311] Trial 2 finished with value: 0.06771929998858095 and parameters: {'n_estimators': 270, 'learning_rate': 0.06258524858828403, 'max_depth': 4}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:36:20,009] Trial 3 finished with value: 0.4288813408681923 and parameters: {'n_estimators': 120, 'learning_rate': 0.034355490277287265, 'max_depth': 3}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:37:06,344] Trial 4 finished with value: -0.0022875138547648888 and parameters: {'n_estimators': 266, 'learning_rate': 0.0680132385735172, 'max_depth': 6}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:37:23,543] Trial 5 finished with value: 0.3424104327939699 and parameters: {'n_estimators': 149, 'learning_rate': 0.022628367217970086, 'max_depth': 4}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:37:43,018] Trial 6 finished with value: 0.4368875862406677 and parameters: {'n_estimators': 135, 'learning_rate': 0.00886759536794929, 'max_depth': 5}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:38:08,108] Trial 7 finished with value: 0.22693272544069754 and parameters: {'n_estimators': 282, 'learning_rate': 0.04371263957339264, 'max_depth': 3}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:38:31,243] Trial 8 finished with value: 0.021969221924520888 and parameters: {'n_estimators': 116, 'learning_rate': 0.04970300967209222, 'max_depth': 7}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:38:55,981] Trial 9 finished with value: 0.5530874945779505 and parameters: {'n_estimators': 283, 'learning_rate': 0.005749187604073283, 'max_depth': 3}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:39:25,363] Trial 10 finished with value: 0.23678841722327226 and parameters: {'n_estimators': 206, 'learning_rate': 0.015775210148002906, 'max_depth': 5}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:39:48,849] Trial 11 finished with value: 0.5281712179522134 and parameters: {'n_estimators': 204, 'learning_rate': 0.005347000056752362, 'max_depth': 4}. Best is trial 0 with value: 0.5829875372366307.
[I 2026-05-23 10:40:07,375] Trial 12 finished with value: 0.5973597098662167 and parameters: {'n_estimators': 215, 'learning_rate': 0.005073743549134538, 'max_depth': 3}. Best is trial 12 with value: 0.5973597098662167.
[I 2026-05-23 10:40:31,228] Trial 13 finished with value: 0.42331888589803013 and parameters: {'n_estimators': 206, 'learning_rate': 0.010090703397787263, 'max_depth': 4}. Best is trial 12 with value: 0.5973597098662167.
[I 2026-05-23 10:40:46,683] Trial 14 finished with value: 0.6175722914410553 and parameters: {'n_estimators': 176, 'learning_rate': 0.0050503689905172545, 'max_depth': 3}. Best is trial 14 with value: 0.6175722914410553.
[I 2026-05-23 10:41:07,198] Trial 15 finished with value: 0.47548604031147756 and parameters: {'n_estimators': 229, 'learning_rate': 0.013298590655387252, 'max_depth': 3}. Best is trial 14 with value: 0.6175722914410553.
[I 2026-05-23 10:41:22,436] Trial 16 finished with value: 0.5786059997788688 and parameters: {'n_estimators': 174, 'learning_rate': 0.007520954565033042, 'max_depth': 3}. Best is trial 14 with value: 0.6175722914410553.
[I 2026-05-23 10:41:57,117] Trial 17 finished with value: 0.0024283982985755515 and parameters: {'n_estimators': 240, 'learning_rate': 0.09233617816592511, 'max_depth': 5}. Best is trial 14 with value: 0.6175722914410553.
[I 2026-05-23 10:42:27,700] Trial 18 finished with value: 0.10012886884980066 and parameters: {'n_estimators': 182, 'learning_rate': 0.023290181162446126, 'max_depth': 6}. Best is trial 14 with value: 0.6175722914410553.
[I 2026-05-23 10:42:32,743] Trial 19 finished with value: 0.6372174545031184 and parameters: {'n_estimators': 52, 'learning_rate': 0.013619204332171618, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:42:42,674] Trial 20 finished with value: 0.3791760272219016 and parameters: {'n_estimators': 53, 'learning_rate': 0.016971469344681824, 'max_depth': 7}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:42:58,148] Trial 21 finished with value: 0.5842571725492892 and parameters: {'n_estimators': 173, 'learning_rate': 0.00713994507362169, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:43:06,240] Trial 22 finished with value: 0.5932553477658054 and parameters: {'n_estimators': 97, 'learning_rate': 0.011705126913199172, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:43:32,189] Trial 23 finished with value: 0.468272700996586 and parameters: {'n_estimators': 226, 'learning_rate': 0.007042443972308269, 'max_depth': 4}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:43:40,677] Trial 24 finished with value: 0.4893495306851584 and parameters: {'n_estimators': 93, 'learning_rate': 0.029929980721058732, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:44:08,782] Trial 25 finished with value: 0.46399066883315254 and parameters: {'n_estimators': 246, 'learning_rate': 0.006619836007478278, 'max_depth': 4}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:44:25,467] Trial 26 finished with value: 0.476718250385905 and parameters: {'n_estimators': 182, 'learning_rate': 0.016754585682362256, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:45:08,050] Trial 27 finished with value: 0.23049509548473657 and parameters: {'n_estimators': 300, 'learning_rate': 0.011211487296179523, 'max_depth': 5}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:45:25,078] Trial 28 finished with value: 0.5533721133855469 and parameters: {'n_estimators': 194, 'learning_rate': 0.008343861430218365, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:45:43,480] Trial 29 finished with value: 0.5728523118975086 and parameters: {'n_estimators': 156, 'learning_rate': 0.005100626866916892, 'max_depth': 4}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:46:01,563] Trial 30 finished with value: 0.5398236505657235 and parameters: {'n_estimators': 159, 'learning_rate': 0.006324050680739615, 'max_depth': 4}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:46:09,506] Trial 31 finished with value: 0.6071863612871572 and parameters: {'n_estimators': 84, 'learning_rate': 0.011707805214537896, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:46:13,879] Trial 32 finished with value: 0.6361777937542972 and parameters: {'n_estimators': 52, 'learning_rate': 0.013788332190859577, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:46:18,845] Trial 33 finished with value: 0.6292418747298948 and parameters: {'n_estimators': 53, 'learning_rate': 0.014624756710280733, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:46:24,947] Trial 34 finished with value: 0.5766222422993567 and parameters: {'n_estimators': 53, 'learning_rate': 0.014572369782222918, 'max_depth': 4}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:46:31,017] Trial 35 finished with value: 0.5828951251452266 and parameters: {'n_estimators': 68, 'learning_rate': 0.018364867998523687, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:46:39,030] Trial 36 finished with value: 0.48798100747744166 and parameters: {'n_estimators': 70, 'learning_rate': 0.019962662607018893, 'max_depth': 4}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:46:49,296] Trial 37 finished with value: 0.47952633159952807 and parameters: {'n_estimators': 114, 'learning_rate': 0.02598844356009744, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:47:12,473] Trial 38 finished with value: 0.2620450875730387 and parameters: {'n_estimators': 136, 'learning_rate': 0.013464515511389536, 'max_depth': 6}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:47:19,566] Trial 39 finished with value: 0.4858477077044757 and parameters: {'n_estimators': 82, 'learning_rate': 0.03509872385637017, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:47:31,597] Trial 40 finished with value: 0.5377803169119026 and parameters: {'n_estimators': 104, 'learning_rate': 0.009761950576506744, 'max_depth': 4}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:47:37,530] Trial 41 finished with value: 0.6340970288891775 and parameters: {'n_estimators': 62, 'learning_rate': 0.011882283494135474, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:47:41,921] Trial 42 finished with value: 0.6002277405582308 and parameters: {'n_estimators': 52, 'learning_rate': 0.020222053361323628, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:47:47,720] Trial 43 finished with value: 0.6231448409180285 and parameters: {'n_estimators': 63, 'learning_rate': 0.013239566017798243, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:47:53,374] Trial 44 finished with value: 0.622751715409344 and parameters: {'n_estimators': 65, 'learning_rate': 0.01288992507886332, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:48:00,637] Trial 45 finished with value: 0.5864825956054401 and parameters: {'n_estimators': 80, 'learning_rate': 0.015113176393692902, 'max_depth': 3}. Best is trial 19 with value: 0.6372174545031184.
[I 2026-05-23 10:48:06,040] Trial 46 finished with value: 0.6403455647007522 and parameters: {'n_estimators': 63, 'learning_rate': 0.010808035413556936, 'max_depth': 3}. Best is trial 46 with value: 0.6403455647007522.
[I 2026-05-23 10:48:13,004] Trial 47 finished with value: 0.6270059042290588 and parameters: {'n_estimators': 77, 'learning_rate': 0.01035025743475637, 'max_depth': 3}. Best is trial 46 with value: 0.6403455647007522.
[I 2026-05-23 10:48:19,731] Trial 48 finished with value: 0.6198921404117439 and parameters: {'n_estimators': 60, 'learning_rate': 0.00883627897704885, 'max_depth': 4}. Best is trial 46 with value: 0.6403455647007522.
[I 2026-05-23 10:48:32,968] Trial 49 finished with value: 0.5212432794806485 and parameters: {'n_estimators': 93, 'learning_rate': 0.00814552646549969, 'max_depth': 5}. Best is trial 46 with value: 0.6403455647007522.
[I 2026-05-23 10:48:42,894] Trial 50 finished with value: 0.5996841819578249 and parameters: {'n_estimators': 111, 'learning_rate': 0.009593344153678903, 'max_depth': 3}. Best is trial 46 with value: 0.6403455647007522.
[I 2026-05-23 10:48:49,603] Trial 51 finished with value: 0.6260661910439888 and parameters: {'n_estimators': 77, 'learning_rate': 0.010487765783035619, 'max_depth': 3}. Best is trial 46 with value: 0.6403455647007522.
[I 2026-05-23 10:48:54,319] Trial 52 finished with value: 0.6539107324886334 and parameters: {'n_estimators': 50, 'learning_rate': 0.011419526017793466, 'max_depth': 3}. Best is trial 52 with value: 0.6539107324886334.
[I 2026-05-23 10:48:58,513] Trial 53 finished with value: 0.6332997657370665 and parameters: {'n_estimators': 50, 'learning_rate': 0.014791595441603227, 'max_depth': 3}. Best is trial 52 with value: 0.6539107324886334.
[I 2026-05-23 10:49:03,160] Trial 54 finished with value: 0.649307661373673 and parameters: {'n_estimators': 50, 'learning_rate': 0.012089954712371134, 'max_depth': 3}. Best is trial 52 with value: 0.6539107324886334.
[I 2026-05-23 10:49:18,083] Trial 55 finished with value: 0.47826807634276103 and parameters: {'n_estimators': 128, 'learning_rate': 0.011596650633307108, 'max_depth': 4}. Best is trial 52 with value: 0.6539107324886334.
[I 2026-05-23 10:49:23,227] Trial 56 finished with value: 0.5982860440125758 and parameters: {'n_estimators': 61, 'learning_rate': 0.017618157613900086, 'max_depth': 3}. Best is trial 52 with value: 0.6539107324886334.
[I 2026-05-23 10:49:31,500] Trial 57 finished with value: 0.5972491355385012 and parameters: {'n_estimators': 90, 'learning_rate': 0.012195001522937855, 'max_depth': 3}. Best is trial 52 with value: 0.6539107324886334.
[I 2026-05-23 10:49:37,589] Trial 58 finished with value: 0.6544345765476309 and parameters: {'n_estimators': 72, 'learning_rate': 0.007922474562885931, 'max_depth': 3}. Best is trial 58 with value: 0.6544345765476309.
[I 2026-05-23 10:49:46,420] Trial 59 finished with value: 0.6157303521891786 and parameters: {'n_estimators': 73, 'learning_rate': 0.007576978055181398, 'max_depth': 4}. Best is trial 58 with value: 0.6544345765476309.
[I 2026-05-23 10:49:55,838] Trial 60 finished with value: 0.6109609402646108 and parameters: {'n_estimators': 103, 'learning_rate': 0.009186055659673762, 'max_depth': 3}. Best is trial 58 with value: 0.6544345765476309.
[I 2026-05-23 10:50:00,949] Trial 61 finished with value: 0.6429380804341671 and parameters: {'n_estimators': 61, 'learning_rate': 0.010814824856391656, 'max_depth': 3}. Best is trial 58 with value: 0.6544345765476309.
[I 2026-05-23 10:50:06,254] Trial 62 finished with value: 0.6864612986399945 and parameters: {'n_estimators': 59, 'learning_rate': 0.005883515525247183, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:50:13,908] Trial 63 finished with value: 0.6574765150890494 and parameters: {'n_estimators': 86, 'learning_rate': 0.006330288878439495, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:50:20,769] Trial 64 finished with value: 0.6740530048557292 and parameters: {'n_estimators': 72, 'learning_rate': 0.005973074608461109, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:50:27,793] Trial 65 finished with value: 0.6681417240029446 and parameters: {'n_estimators': 84, 'learning_rate': 0.005591916188237849, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:50:35,682] Trial 66 finished with value: 0.6646301450960126 and parameters: {'n_estimators': 86, 'learning_rate': 0.005746256193727789, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:50:52,516] Trial 67 finished with value: 0.5174245520509546 and parameters: {'n_estimators': 88, 'learning_rate': 0.00578462158756375, 'max_depth': 7}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:51:01,587] Trial 68 finished with value: 0.652565603862913 and parameters: {'n_estimators': 99, 'learning_rate': 0.005906572400761689, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:51:11,278] Trial 69 finished with value: 0.6371260020177838 and parameters: {'n_estimators': 107, 'learning_rate': 0.006630371738760576, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:51:31,054] Trial 70 finished with value: 0.5102902368812227 and parameters: {'n_estimators': 120, 'learning_rate': 0.005379804040046025, 'max_depth': 6}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:51:39,925] Trial 71 finished with value: 0.6542201698162702 and parameters: {'n_estimators': 98, 'learning_rate': 0.005844835713681947, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:51:46,061] Trial 72 finished with value: 0.6726868220681196 and parameters: {'n_estimators': 73, 'learning_rate': 0.006008644062289563, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:51:53,938] Trial 73 finished with value: 0.6590759882746723 and parameters: {'n_estimators': 86, 'learning_rate': 0.006181838586903203, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:52:01,874] Trial 74 finished with value: 0.6567143103130786 and parameters: {'n_estimators': 87, 'learning_rate': 0.006328146862867657, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:52:09,378] Trial 75 finished with value: 0.6487972109829985 and parameters: {'n_estimators': 88, 'learning_rate': 0.0069587137066981575, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:52:19,071] Trial 76 finished with value: 0.6220794917146621 and parameters: {'n_estimators': 83, 'learning_rate': 0.006255424074625991, 'max_depth': 4}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:52:25,643] Trial 77 finished with value: 0.6789840849074016 and parameters: {'n_estimators': 73, 'learning_rate': 0.005430831546875901, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:52:32,186] Trial 78 finished with value: 0.6782743242171951 and parameters: {'n_estimators': 73, 'learning_rate': 0.005484936410215548, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:52:38,754] Trial 79 finished with value: 0.6779142189489794 and parameters: {'n_estimators': 73, 'learning_rate': 0.0055215307502050415, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:52:44,830] Trial 80 finished with value: 0.6862022616838277 and parameters: {'n_estimators': 70, 'learning_rate': 0.0050071801984614165, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:52:51,858] Trial 81 finished with value: 0.6798139726080651 and parameters: {'n_estimators': 75, 'learning_rate': 0.005209545922497943, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:52:58,067] Trial 82 finished with value: 0.6801231435896979 and parameters: {'n_estimators': 73, 'learning_rate': 0.005316016388503154, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:53:04,931] Trial 83 finished with value: 0.6823601782704889 and parameters: {'n_estimators': 74, 'learning_rate': 0.005054234279731144, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:53:10,517] Trial 84 finished with value: 0.6857620731055658 and parameters: {'n_estimators': 67, 'learning_rate': 0.005275307736006105, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:53:16,668] Trial 85 finished with value: 0.6862668714587156 and parameters: {'n_estimators': 68, 'learning_rate': 0.005134373385868164, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:53:23,462] Trial 86 finished with value: 0.6789611653918812 and parameters: {'n_estimators': 78, 'learning_rate': 0.005093347419609923, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:53:30,405] Trial 87 finished with value: 0.6689575806991671 and parameters: {'n_estimators': 57, 'learning_rate': 0.005329344041263364, 'max_depth': 4}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:53:37,002] Trial 88 finished with value: 0.6778628254003984 and parameters: {'n_estimators': 79, 'learning_rate': 0.005106717396591888, 'max_depth': 3}. Best is trial 62 with value: 0.6864612986399945.
[I 2026-05-23 10:53:43,206] Trial 89 finished with value: 0.6880155540888018 and parameters: {'n_estimators': 66, 'learning_rate': 0.005126693121267765, 'max_depth': 3}. Best is trial 89 with value: 0.6880155540888018.
[I 2026-05-23 10:53:49,657] Trial 90 finished with value: 0.6455509991635758 and parameters: {'n_estimators': 59, 'learning_rate': 0.006912903860358173, 'max_depth': 4}. Best is trial 89 with value: 0.6880155540888018.

In [ ]:
best_gbr_si

{'n_estimators': 50, 'learning_rate': 0.00500800000856754, 'max_depth': 3}

In [ ]:
best_lgbm_si

{'n_estimators': 50, 'learning_rate': 0.005000320565186036, 'num_leaves': 45}

In [ ]:
best_rf_si

{'n_estimators': 57, 'max_depth': 5, 'max_features': 'log2'}

In [17]:
best_rf_si={'n_estimators': 57, 'max_depth': 5, 'max_features': 'log2'}
best_lgbm_si={'n_estimators': 50, 'learning_rate': 0.005000320565186036, 'num_leaves': 45}
best_gbr_si={'n_estimators': 50, 'learning_rate': 0.00500800000856754, 'max_depth': 3}

In [18]:
# 3. Сравнение и финальная оценка SI
si_results = []
models_si = {
    "GBR": GradientBoostingRegressor(**best_gbr_si, random_state=42),
    "RF": RandomForestRegressor(**best_rf_si, random_state=42),
    "LGBM": lgb.LGBMRegressor(**best_lgbm_si, random_state=42, verbosity=-1)
}

for name, model in models_si.items():
    model.fit(X_train_si, y_train_si)
    p_tr = model.predict(X_train_si)
    p_te = model.predict(X_test_si)
    si_results.append({
        "Model": name,
        "Train RMSE": np.sqrt(mean_squared_error(y_train_si, p_tr)),
        "Test RMSE": np.sqrt(mean_squared_error(y_test_si, p_te)),
        "Test R2": r2_score(y_test_si, p_te)
    })

display(pd.DataFrame(si_results))

  Model  Train RMSE  Test RMSE   Test R2
0   GBR    0.717108   0.723575  0.053612
1    RF    0.591767   0.662566  0.206474
2  LGBM    0.690771   0.710958  0.086328

видно что нам удалоьс незначительно улучшить метрику модели на тестовых данных , но зато теперь предсказания моделей стабильны на трейне и тесте, нет переобучения.

In [19]:
# Оценка на отфильтрованных данных
df_si_f = df_si[df_si['is_outlier'] == 1].copy()
X_si_f = df_si_f[relevant_features_si]
y_si_f = np.log10(df_si_f[target_si])
X_tr_f, X_te_f, y_tr_f, y_te_f = train_test_split(X_si_f, y_si_f, test_size=0.2, random_state=42)

final_model_si = RandomForestRegressor(**best_rf_si, random_state=42)
final_model_si.fit(X_tr_f, y_tr_f)
f_preds_si = final_model_si.predict(X_te_f)

print(f"\nFinal SI Results (Outliers Removed):")
print(f"RMSE: {np.sqrt(mean_squared_error(y_te_f, f_preds_si)):.4f}")
print(f"R2:   {r2_score(y_te_f, f_preds_si):.4f}")

Final SI Results (Outliers Removed):
RMSE: 0.6855
R2:   0.2370

в данной задачен исключение выбросов не дало улчшения скора, возможно выбросы имеют смысл для данной задачи